/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

struct Coin;
struct Game;
struct Ghost;
struct Pacman;
struct Powerup;
struct _1_run_game__opaque_Node_1;
struct _IO_FILE;
struct key_sample_t;
struct timeval;
extern void exit(int status ) ;
typedef unsigned char uint8_t;
typedef struct key_sample_t key_sample_t;
typedef struct Coin coin_t;
typedef long __clock_t;
typedef __clock_t clock_t;
typedef struct Game game_t;
void pickup_powerups(game_t *game ) ;
extern int fclose(void *stream ) ;
struct key_sample_t {
   _Bool w ;
   _Bool a ;
   _Bool s ;
   _Bool d ;
   _Bool q ;
};
typedef int int32_t;
struct Powerup {
   _Bool taken ;
   int32_t x ;
   int32_t y ;
};
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern int raise(int sig ) ;
void end_game(game_t *game ) ;
extern void abort() ;
struct Ghost {
   _Bool alive ;
   int32_t x ;
   int32_t y ;
};
struct _1_run_game__opaque_Node_1 {
   int data ;
   struct _1_run_game__opaque_Node_1 *next ;
};
struct _1_run_game__opaque_Node_1 *_1_run_game__opaque_list1_1  =    (struct _1_run_game__opaque_Node_1 *)0;
extern void *malloc(unsigned long size ) ;
void collide_ghosts(game_t *game ) ;
extern int rand() ;
extern unsigned long strlen(char const   *s ) ;
int main(int argc , char **argv ) ;
typedef unsigned long uint64_t;
struct Pacman {
   _Bool alive ;
   int32_t x ;
   int32_t y ;
   uint8_t lives ;
   double powerup_time ;
};
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern int gettimeofday(struct timeval *tv , void *tz  , ...) ;
void megaInit(void) ;
struct Coin {
   _Bool taken ;
   int32_t x ;
   int32_t y ;
};
typedef struct Ghost ghost_t;
typedef struct Pacman pacman_t;
typedef struct Powerup powerup_t;
typedef unsigned int uint32_t;
struct Game {
   uint32_t pts ;
   pacman_t pacman ;
   ghost_t ghosts[4] ;
   coin_t coins[128] ;
   powerup_t powerups[4] ;
};
void steer_ghosts(ghost_t *ghosts ) ;
void steer_pacman(pacman_t *pacman , key_sample_t *input ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
extern int scanf(char const   *format  , ...) ;
extern  __attribute__((__nothrow__)) clock_t ( __attribute__((__leaf__)) clock)(void) ;
key_sample_t sample_input(void) ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned long strnlen(char const   *s , unsigned long maxlen ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
struct _1_run_game__opaque_Node_1 *_1_run_game__opaque_list2_1  =    (struct _1_run_game__opaque_Node_1 *)0;
game_t start_game(void) ;
extern void signal(int sig , void *func ) ;
typedef struct _IO_FILE FILE;
typedef struct _1_run_game__opaque_Node_1 *_1_run_game__opaque_List_1;
void init(void) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
void run_game(game_t *game ) ;
void pickup_coins(game_t *game ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned long size ) ;
void cleanup(void) ;
key_sample_t sample_input(void) 
{ 
  key_sample_t sample ;

  {
  sample.w = (_Bool)1;
  sample.a = (_Bool)0;
  sample.s = (_Bool)0;
  sample.d = (_Bool)0;
  sample.q = (_Bool)0;
  return (sample);
}
}
void steer_ghosts(ghost_t *ghosts ) 
{ 
  uint32_t i ;
  ghost_t *ghost ;
  int32_t x ;
  int32_t y ;
  int tmp ;

  {
  i = (uint32_t )0;
  while (i < 4U) {
    ghost = ghosts + i;
    if (! ghost->alive) {
      goto __Cont;
    }
    x = (int32_t )(i - 2U);
    if (x < 0) {
      tmp = -1;
    } else {
      tmp = 1;
    }
    y = tmp;
    ghost->x += x;
    ghost->y += y;
    __Cont: /* CIL Label */ 
    i ++;
  }
  return;
}
}
game_t start_game(void) 
{ 
  uint32_t width ;
  uint32_t height ;
  game_t game ;
  pacman_t __constr_expr_0 ;
  ghost_t __constr_expr_1 ;
  ghost_t __constr_expr_2 ;
  ghost_t __constr_expr_3 ;
  ghost_t __constr_expr_4 ;
  powerup_t __constr_expr_5 ;
  powerup_t __constr_expr_6 ;
  powerup_t __constr_expr_7 ;
  powerup_t __constr_expr_8 ;
  uint32_t i ;
  int32_t x ;
  int32_t y ;
  coin_t __constr_expr_9 ;

  {
  width = (uint32_t )12;
  height = (uint32_t )12;
  game.pts = (uint32_t )0;
  __constr_expr_0.alive = (_Bool)1;
  __constr_expr_0.x = 0;
  __constr_expr_0.y = 0;
  __constr_expr_0.lives = (uint8_t )3;
  __constr_expr_0.powerup_time = (double )0;
  game.pacman = __constr_expr_0;
  __constr_expr_1.alive = (_Bool)1;
  __constr_expr_1.x = (int32_t )(- width / 2U);
  __constr_expr_1.y = (int32_t )(- height / 2U);
  game.ghosts[0] = __constr_expr_1;
  __constr_expr_2.alive = (_Bool)1;
  __constr_expr_2.x = (int32_t )(width / 2U);
  __constr_expr_2.y = (int32_t )(- height / 2U);
  game.ghosts[1] = __constr_expr_2;
  __constr_expr_3.alive = (_Bool)1;
  __constr_expr_3.x = (int32_t )(width / 2U);
  __constr_expr_3.y = (int32_t )(height / 2U);
  game.ghosts[2] = __constr_expr_3;
  __constr_expr_4.alive = (_Bool)1;
  __constr_expr_4.x = (int32_t )(- width / 2U);
  __constr_expr_4.y = (int32_t )(height / 2U);
  game.ghosts[3] = __constr_expr_4;
  __constr_expr_5.taken = (_Bool)0;
  __constr_expr_5.x = (int32_t )width;
  __constr_expr_5.y = (int32_t )(- height);
  game.powerups[0] = __constr_expr_5;
  __constr_expr_6.taken = (_Bool)0;
  __constr_expr_6.x = (int32_t )width;
  __constr_expr_6.y = (int32_t )height;
  game.powerups[1] = __constr_expr_6;
  __constr_expr_7.taken = (_Bool)0;
  __constr_expr_7.x = (int32_t )(- width);
  __constr_expr_7.y = (int32_t )height;
  game.powerups[2] = __constr_expr_7;
  __constr_expr_8.taken = (_Bool)0;
  __constr_expr_8.x = (int32_t )(- width);
  __constr_expr_8.y = (int32_t )(- height);
  game.powerups[3] = __constr_expr_8;
  i = (uint32_t )0;
  while (i < 128U) {
    x = (int32_t )(i % width);
    y = (int32_t )(i / width);
    __constr_expr_9.taken = (_Bool)0;
    __constr_expr_9.x = x;
    __constr_expr_9.y = y;
    game.coins[i] = __constr_expr_9;
    i ++;
  }
  return (game);
}
}
void megaInit(void) 
{ 


  {

}
}
void pickup_powerups(game_t *game ) 
{ 
  uint32_t i ;
  powerup_t *powerup ;

  {
  i = (uint32_t )0;
  while (i < 4U) {
    powerup = & game->powerups[i];
    if (powerup->taken) {
      goto __Cont;
    }
    if (powerup->x != game->pacman.x) {
      goto __Cont;
    }
    if (powerup->y != game->pacman.y) {
      goto __Cont;
    }
    powerup->taken = (_Bool)1;
    game->pacman.powerup_time += (double )30;
    __Cont: /* CIL Label */ 
    i ++;
  }
  return;
}
}
void cleanup(void) 
{ 


  {
  return;
}
}
void pickup_coins(game_t *game ) 
{ 
  uint32_t i ;
  coin_t *coin ;

  {
  i = (uint32_t )0;
  while (i < 128U) {
    coin = & game->coins[i];
    if (coin->taken) {
      goto __Cont;
    }
    if (coin->x != game->pacman.x) {
      goto __Cont;
    }
    if (coin->y != game->pacman.y) {
      goto __Cont;
    }
    coin->taken = (_Bool)1;
    (game->pts) ++;
    __Cont: /* CIL Label */ 
    i ++;
  }
  return;
}
}
int main(int argc , char **argv ) 
{ 
  game_t game ;
  game_t tmp ;

  {
  megaInit();
  init();
  while (1) {
    tmp = start_game();
    game = tmp;
    run_game(& game);
    end_game(& game);
  }
  cleanup();
}
}
void end_game(game_t *game ) 
{ 


  {
  printf((char const   */* __restrict  */)"You got %d points!\n", game->pts);
  return;
}
}
void collide_ghosts(game_t *game ) 
{ 
  uint32_t i ;
  ghost_t *ghost ;

  {
  i = (uint32_t )0;
  while (i < 4U) {
    ghost = & game->ghosts[i];
    if (! ghost->alive) {
      goto __Cont;
    }
    if (ghost->x != game->pacman.x) {
      goto __Cont;
    }
    if (ghost->y != game->pacman.y) {
      goto __Cont;
    }
    if (game->pacman.powerup_time > (double )0) {
      game->pts += 30U;
      ghost->alive = (_Bool)0;
    } else {
      game->pacman.lives = (uint8_t )((int )game->pacman.lives - 1);
      game->pacman.x = 0;
      game->pacman.y = 0;
      game->pacman.alive = (_Bool )((int )game->pacman.lives > 0);
    }
    __Cont: /* CIL Label */ 
    i ++;
  }
  return;
}
}
void steer_pacman(pacman_t *pacman , key_sample_t *input ) 
{ 


  {
  if (input->w) {
    (pacman->y) --;
  }
  if (input->s) {
    (pacman->y) ++;
  }
  if (input->a) {
    (pacman->x) --;
  }
  if (input->d) {
    (pacman->x) ++;
  }
  return;
}
}
void init(void) 
{ 


  {
  return;
}
}
void run_game(game_t *game ) 
{ 
  double acc ;
  uint64_t runs ;
  clock_t start ;
  clock_t tmp ;
  uint32_t k ;
  key_sample_t input ;
  key_sample_t tmp___0 ;
  clock_t finish ;
  clock_t tmp___1 ;
  double time___0 ;
  int i12 ;
  int r13 ;
  struct _1_run_game__opaque_Node_1 *p14 ;
  int _1_run_game__BEGIN_0 ;
  int _1_run_game__END_0 ;
  int _1_run_game__BARRIER_1 ;
  unsigned long _2_run_game_next ;

  {
  {  /* __blockattribute__(__ATOMIC__)*/ 
  _1_run_game__BEGIN_0 = 1;
  i12 = 0;
  while (i12 < 2) {
    r13 = rand();
    p14 = (struct _1_run_game__opaque_Node_1 *)malloc(sizeof(struct _1_run_game__opaque_Node_1 ));
    if (p14 != (struct _1_run_game__opaque_Node_1 *)0UL) {
      p14->data = r13;
      if (_1_run_game__opaque_list1_1 != (struct _1_run_game__opaque_Node_1 *)0UL) {
        p14->next = _1_run_game__opaque_list1_1->next;
        _1_run_game__opaque_list1_1->next = p14;
      } else {
        p14->next = p14;
        _1_run_game__opaque_list1_1 = p14;
      }
    } else {

    }
    i12 ++;
  }
  _1_run_game__opaque_list2_1 = _1_run_game__opaque_list1_1;
  _1_run_game__END_0 = 1;
  }
  _1_run_game__BARRIER_1 = 1;
  _2_run_game_next = 27 + ((_1_run_game__opaque_list1_1 == (struct _1_run_game__opaque_Node_1 *)0UL) + (_1_run_game__opaque_list1_1 == (struct _1_run_game__opaque_Node_1 *)0UL));
  while (1) {
    switch (_2_run_game_next) {
    case 4: 
    k ++;
    _2_run_game_next = _1_run_game__opaque_list1_1 != (struct _1_run_game__opaque_Node_1 *)0UL ? 21 : i12;
    break;
    case 18: 
    tmp___1 = clock();
    _2_run_game_next = ((unsigned long )(_1_run_game__opaque_list2_1 == (struct _1_run_game__opaque_Node_1 *)0UL) + (unsigned long )(_1_run_game__opaque_list1_1 == _1_run_game__opaque_list2_1)) + ((unsigned long )(_1_run_game__opaque_list1_1 != (struct _1_run_game__opaque_Node_1 *)0UL) + (unsigned long )(! ((unsigned long )(_1_run_game__opaque_list1_1 == (struct _1_run_game__opaque_Node_1 *)0UL))));
    break;
    case 5: 
    collide_ghosts(game);
    _2_run_game_next = 4 + ((_1_run_game__opaque_list1_1 != _1_run_game__opaque_list2_1) + (_1_run_game__opaque_list1_1 != _1_run_game__opaque_list2_1));
    break;
    case 21: ;
    if (k < 1000U) {
      _2_run_game_next = _1_run_game__opaque_list1_1 == _1_run_game__opaque_list2_1 ? 19 : r13;
    } else {
      _2_run_game_next = 18 - ! (_1_run_game__opaque_list1_1 == _1_run_game__opaque_list2_1);
    }
    break;
    case 19: 
    tmp___0 = sample_input();
    _2_run_game_next = 10 - ((_1_run_game__opaque_list1_1 != (struct _1_run_game__opaque_Node_1 *)0UL) - (_1_run_game__opaque_list1_1 != (struct _1_run_game__opaque_Node_1 *)0UL));
    break;
    case 8: 
    steer_ghosts((ghost_t *)(game->ghosts));
    _2_run_game_next = 7 - ((_1_run_game__opaque_list1_1 == (struct _1_run_game__opaque_Node_1 *)0UL) + (_1_run_game__opaque_list1_1 == (struct _1_run_game__opaque_Node_1 *)0UL));
    break;
    case 14: ;
    return;
    break;
    case 7: 
    pickup_coins(game);
    _2_run_game_next = 6 * ! (_1_run_game__opaque_list2_1 == (struct _1_run_game__opaque_Node_1 *)0UL);
    break;
    case 15: 
    acc += time___0;
    _2_run_game_next = (unsigned long )(_1_run_game__opaque_list1_1 != (struct _1_run_game__opaque_Node_1 *)0UL) - (unsigned long )(_1_run_game__opaque_list2_1 == (struct _1_run_game__opaque_Node_1 *)0UL);
    break;
    case 17: ;
    if (game->pacman.powerup_time > (double )0) {
      _2_run_game_next = _1_run_game__opaque_list2_1 != (struct _1_run_game__opaque_Node_1 *)0UL ? 16 : 16 * 10;
    } else {
      _2_run_game_next = 15 * ! (_1_run_game__opaque_list1_1 != _1_run_game__opaque_list2_1);
    }
    break;
    case 16: 
    game->pacman.powerup_time -= time___0;
    _2_run_game_next = _1_run_game__opaque_list2_1 == (struct _1_run_game__opaque_Node_1 *)0UL ? 15 + r13 : 15;
    break;
    case 3: 
    finish = tmp___1;
    _2_run_game_next = (unsigned long )(_1_run_game__opaque_list1_1 == _1_run_game__opaque_list2_1) + (unsigned long )(! ((unsigned long )(_1_run_game__opaque_list1_1 == (struct _1_run_game__opaque_Node_1 *)0UL)));
    break;
    case 13: 
    runs = (uint64_t )0;
    _2_run_game_next = 25 - (_1_run_game__opaque_list1_1 != _1_run_game__opaque_list2_1);
    break;
    case 12: 
    start = tmp;
    _2_run_game_next = 11 + ! (_1_run_game__opaque_list1_1 == _1_run_game__opaque_list2_1);
    break;
    case 2: 
    time___0 = (double )(finish - start) / (double )1000000L;
    _2_run_game_next = 17 + ((_1_run_game__opaque_list1_1 == _1_run_game__opaque_list2_1) - (_1_run_game__opaque_list1_1 == _1_run_game__opaque_list2_1));
    break;
    case 11: 
    k = (uint32_t )0;
    _2_run_game_next = 21 + (_1_run_game__opaque_list1_1 == (struct _1_run_game__opaque_Node_1 *)0UL);
    break;
    case 23: 
    tmp = clock();
    _2_run_game_next = _1_run_game__opaque_list1_1 == (struct _1_run_game__opaque_Node_1 *)0UL ? 4 : 12;
    break;
    case 0: 
    printf((char const   */* __restrict  */)"%f\n", acc / (double )runs);
    _2_run_game_next = _1_run_game__opaque_list1_1 == (struct _1_run_game__opaque_Node_1 *)0UL ? 25 << i12 : 25;
    break;
    case 1: 
    runs ++;
    _2_run_game_next = (unsigned long )(_1_run_game__opaque_list1_1 != (struct _1_run_game__opaque_Node_1 *)0UL) - (unsigned long )(_1_run_game__opaque_list1_1 != (struct _1_run_game__opaque_Node_1 *)0UL);
    break;
    case 10: 
    input = tmp___0;
    _2_run_game_next = 9 + ! (_1_run_game__opaque_list1_1 == _1_run_game__opaque_list2_1);
    break;
    case 25: ;
    if (game->pacman.alive) {
      _2_run_game_next = 23 - (_1_run_game__opaque_list1_1 != _1_run_game__opaque_list2_1);
    } else {
      _2_run_game_next = 14 * (_1_run_game__opaque_list1_1 == _1_run_game__opaque_list2_1);
    }
    break;
    case 9: 
    steer_pacman(& game->pacman, & input);
    _2_run_game_next = _1_run_game__opaque_list1_1 != _1_run_game__opaque_list2_1 ? 8 - 5 : 8;
    break;
    case 6: 
    pickup_powerups(game);
    _2_run_game_next = _1_run_game__opaque_list1_1 == (struct _1_run_game__opaque_Node_1 *)0UL ? 5 + i12 : 5;
    break;
    case 27: 
    acc = (double )0;
    _2_run_game_next = 13 * (_1_run_game__opaque_list2_1 != (struct _1_run_game__opaque_Node_1 *)0UL);
    break;
    }
  }
}
}
